/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'native-vcp.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./native-vcp.android-arm64.node')
          } else {
            nativeBinding = require('native-vcp-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'native-vcp.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./native-vcp.android-arm-eabi.node')
          } else {
            nativeBinding = require('native-vcp-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'native-vcp.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./native-vcp.win32-x64-msvc.node')
          } else {
            nativeBinding = require('native-vcp-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'native-vcp.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./native-vcp.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('native-vcp-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'native-vcp.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./native-vcp.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('native-vcp-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'native-vcp.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./native-vcp.darwin-universal.node')
      } else {
        nativeBinding = require('native-vcp-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'native-vcp.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./native-vcp.darwin-x64.node')
          } else {
            nativeBinding = require('native-vcp-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'native-vcp.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./native-vcp.darwin-arm64.node')
          } else {
            nativeBinding = require('native-vcp-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'native-vcp.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./native-vcp.freebsd-x64.node')
      } else {
        nativeBinding = require('native-vcp-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'native-vcp.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./native-vcp.linux-x64-musl.node')
            } else {
              nativeBinding = require('native-vcp-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'native-vcp.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./native-vcp.linux-x64-gnu.node')
            } else {
              nativeBinding = require('native-vcp-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'native-vcp.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./native-vcp.linux-arm64-musl.node')
            } else {
              nativeBinding = require('native-vcp-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'native-vcp.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./native-vcp.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('native-vcp-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'native-vcp.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./native-vcp.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('native-vcp-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'native-vcp.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./native-vcp.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('native-vcp-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'native-vcp.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./native-vcp.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('native-vcp-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'native-vcp.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./native-vcp.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('native-vcp-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'native-vcp.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./native-vcp.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('native-vcp-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { ChineseSearchEngine, jiebaCut, jiebaExtractKeywords, TextChunker, quickChunk, estimateTokenCount, CooccurrenceMatrix, UnifiedDatabase, HybridSearchEngine, quickRrfFusion, computeRrfScore, multiSourceFusion, SearchEngine, SemanticGroupType, SemanticGroupMatcher, TagCooccurrenceMatrix, setLogCallback, createTraceId, createSpanId, Tracer, cosineSimilarity, euclideanDistance, dotProduct, normalize, batchCosineSimilarity, topKSimilar, VectorStore, VexusIndex, getVersion, initialize, healthCheck } = nativeBinding

module.exports.ChineseSearchEngine = ChineseSearchEngine
module.exports.jiebaCut = jiebaCut
module.exports.jiebaExtractKeywords = jiebaExtractKeywords
module.exports.TextChunker = TextChunker
module.exports.quickChunk = quickChunk
module.exports.estimateTokenCount = estimateTokenCount
module.exports.CooccurrenceMatrix = CooccurrenceMatrix
module.exports.UnifiedDatabase = UnifiedDatabase
module.exports.HybridSearchEngine = HybridSearchEngine
module.exports.quickRrfFusion = quickRrfFusion
module.exports.computeRrfScore = computeRrfScore
module.exports.multiSourceFusion = multiSourceFusion
module.exports.SearchEngine = SearchEngine
module.exports.SemanticGroupType = SemanticGroupType
module.exports.SemanticGroupMatcher = SemanticGroupMatcher
module.exports.TagCooccurrenceMatrix = TagCooccurrenceMatrix
module.exports.setLogCallback = setLogCallback
module.exports.createTraceId = createTraceId
module.exports.createSpanId = createSpanId
module.exports.Tracer = Tracer
module.exports.cosineSimilarity = cosineSimilarity
module.exports.euclideanDistance = euclideanDistance
module.exports.dotProduct = dotProduct
module.exports.normalize = normalize
module.exports.batchCosineSimilarity = batchCosineSimilarity
module.exports.topKSimilar = topKSimilar
module.exports.VectorStore = VectorStore
module.exports.VexusIndex = VexusIndex
module.exports.getVersion = getVersion
module.exports.initialize = initialize
module.exports.healthCheck = healthCheck
