/**
 * EnvConfigLoader - .env 格式配置解析器
 *
 * 用于导入/导出 VCPToolBox 兼容的 .env 格式变量配置。
 * 支持 Tar、Var、Sar 变量格式。
 *
 * @example
 * ```typescript
 * const loader = new EnvConfigLoader()
 *
 * // 解析 .env 内容
 * const variables = loader.parseEnvContent(envFileContent)
 *
 * // 导出为 .env 格式
 * const envContent = loader.exportToEnv(variables)
 * ```
 */

import { loggerService } from '@main/services/LoggerService'
import type { VCPVariable, VariableScope, VariableSource } from '@shared/variables'

const logger = loggerService.withContext('EnvConfigLoader')

/**
 * 变量类别映射（根据变量名前缀推断）
 */
const CATEGORY_MAP: Record<string, string> = {
  Tar: '功能指南',
  Var: '基础变量',
  Sar: '系统变量',
  VCP: '插件变量'
}

/**
 * .env 格式配置解析器
 */
export class EnvConfigLoader {
  /**
   * 从 .env 内容解析变量列表
   *
   * 支持的格式：
   * - 标准格式: KEY=value
   * - 带引号: KEY="value with spaces"
   * - 带单引号: KEY='value'
   * - 多行值: KEY="line1\nline2"
   * - 注释: # comment
   *
   * @param content .env 文件内容
   * @returns 解析后的变量列表
   */
  parseEnvContent(content: string): Partial<VCPVariable>[] {
    const variables: Partial<VCPVariable>[] = []
    const lines = content.split('\n')

    let currentKey: string | null = null
    let currentValue: string[] = []
    let inMultiline = false

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i]
      const trimmed = line.trim()

      // 跳过空行和注释
      if (!trimmed || trimmed.startsWith('#')) {
        // 如果正在处理多行值，注释也作为内容的一部分
        if (inMultiline) {
          currentValue.push(line)
        }
        continue
      }

      if (inMultiline) {
        // 继续收集多行值
        currentValue.push(line)

        // 检查是否结束（以引号结尾）
        if (trimmed.endsWith('"') || trimmed.endsWith("'")) {
          inMultiline = false
          if (currentKey) {
            const value = this.parseMultilineValue(currentValue.join('\n'))
            const variable = this.createVariableFromEnv(currentKey, value)
            if (variable) {
              variables.push(variable)
            }
          }
          currentKey = null
          currentValue = []
        }
        continue
      }

      // 解析 KEY=value 格式
      const match = trimmed.match(/^([a-zA-Z_][a-zA-Z0-9_]*)=(.*)$/)
      if (!match) continue

      const [, key, rawValue] = match

      // 只处理 Tar/Var/Sar/VCP 开头的变量
      if (!this.isVCPVariable(key)) {
        continue
      }

      // 检查是否是多行值（以引号开始但不以引号结束）
      if (
        (rawValue.startsWith('"') && !rawValue.endsWith('"')) ||
        (rawValue.startsWith("'") && !rawValue.endsWith("'"))
      ) {
        inMultiline = true
        currentKey = key
        currentValue = [rawValue]
        continue
      }

      // 单行值
      const value = this.parseValue(rawValue)
      const variable = this.createVariableFromEnv(key, value)
      if (variable) {
        variables.push(variable)
      }
    }

    // 处理未完成的多行值
    if (currentKey && currentValue.length > 0) {
      const value = this.parseMultilineValue(currentValue.join('\n'))
      const variable = this.createVariableFromEnv(currentKey, value)
      if (variable) {
        variables.push(variable)
      }
    }

    logger.info('Parsed env content', { variableCount: variables.length })
    return variables
  }

  /**
   * 导出变量列表为 .env 格式
   *
   * @param variables 变量列表
   * @returns .env 格式的字符串
   */
  exportToEnv(variables: Array<Partial<VCPVariable> & { name: string; value: string }>): string {
    const lines: string[] = [
      '# VCP Variables Configuration',
      '# Generated by Cherry Studio',
      `# Generated at: ${new Date().toISOString()}`,
      ''
    ]

    // 按类别分组
    const grouped = this.groupByCategory(variables)

    for (const [category, vars] of Object.entries(grouped)) {
      if (vars.length === 0) continue

      lines.push(`# ==================== ${category} ====================`)

      for (const v of vars) {
        // 添加描述注释
        if (v.description) {
          lines.push(`# ${v.description}`)
        }

        // 格式化值
        const formattedValue = this.formatValue(v.value)
        lines.push(`${v.name}=${formattedValue}`)
        lines.push('')
      }
    }

    return lines.join('\n')
  }

  /**
   * 检查变量名是否为 VCP 变量
   */
  private isVCPVariable(key: string): boolean {
    return key.startsWith('Tar') || key.startsWith('Var') || key.startsWith('Sar') || key.startsWith('VCP')
  }

  /**
   * 解析单行值
   */
  private parseValue(rawValue: string): string {
    let value = rawValue.trim()

    // 移除引号
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1)
    }

    // 处理转义字符
    value = value.replace(/\\n/g, '\n').replace(/\\t/g, '\t').replace(/\\r/g, '\r').replace(/\\\\/g, '\\')

    return value
  }

  /**
   * 解析多行值
   */
  private parseMultilineValue(rawValue: string): string {
    let value = rawValue.trim()

    // 移除首尾引号
    if (value.startsWith('"')) {
      value = value.slice(1)
    }
    if (value.endsWith('"')) {
      value = value.slice(0, -1)
    }
    if (value.startsWith("'")) {
      value = value.slice(1)
    }
    if (value.endsWith("'")) {
      value = value.slice(0, -1)
    }

    return value
  }

  /**
   * 格式化值用于导出
   */
  private formatValue(value: string): string {
    // 如果包含换行或特殊字符，使用双引号包裹
    if (value.includes('\n') || value.includes('"') || value.includes("'") || value.includes(' ')) {
      // 转义内部双引号
      const escaped = value.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n')
      return `"${escaped}"`
    }

    return value
  }

  /**
   * 从 .env 键值对创建变量对象
   */
  private createVariableFromEnv(key: string, value: string): Partial<VCPVariable> | null {
    const now = Date.now()

    // 推断类别
    let category = '自定义变量'
    for (const [prefix, cat] of Object.entries(CATEGORY_MAP)) {
      if (key.startsWith(prefix)) {
        category = cat
        break
      }
    }

    // 推断作用域
    let scope: VariableScope = 'global'
    if (key.startsWith('Sar')) {
      scope = 'agent' // Sar 变量通常与模型相关
    }

    // 推断来源
    const source: VariableSource = 'env'

    // 检查是否为 .txt 文件引用
    const isTxtReference = value.toLowerCase().endsWith('.txt')

    return {
      id: `env_${key}_${now}`,
      name: key,
      value,
      description: isTxtReference ? `从 ${value} 加载内容` : undefined,
      category,
      scope,
      source,
      createdAt: now,
      updatedAt: now
    }
  }

  /**
   * 按类别分组变量
   */
  private groupByCategory(
    variables: Array<Partial<VCPVariable> & { name: string; value: string }>
  ): Record<string, Array<Partial<VCPVariable> & { name: string; value: string }>> {
    const grouped: Record<string, Array<Partial<VCPVariable> & { name: string; value: string }>> = {
      功能指南: [],
      基础变量: [],
      系统变量: [],
      插件变量: [],
      自定义变量: []
    }

    for (const v of variables) {
      const category = v.category || '自定义变量'
      if (!grouped[category]) {
        grouped[category] = []
      }
      grouped[category].push(v)
    }

    return grouped
  }

  /**
   * 解析 SarModel/SarPrompt 配对
   *
   * VCPToolBox 格式：
   * SarModel1=gpt-4,claude-3
   * SarPrompt1=特殊指令内容
   *
   * @param content .env 文件内容
   * @returns Sar 配对列表
   */
  parseSarPairs(content: string): Array<{
    index: number
    models: string[]
    prompt: string
  }> {
    const pairs: Array<{ index: number; models: string[]; prompt: string }> = []
    const variables = this.parseEnvContent(content)

    // 收集所有 SarModel 和 SarPrompt
    const sarModels = new Map<number, string>()
    const sarPrompts = new Map<number, string>()

    for (const v of variables) {
      if (!v.name) continue

      const modelMatch = v.name.match(/^SarModel(\d+)$/)
      if (modelMatch && v.value) {
        sarModels.set(parseInt(modelMatch[1], 10), v.value)
      }

      const promptMatch = v.name.match(/^SarPrompt(\d+)$/)
      if (promptMatch && v.value) {
        sarPrompts.set(parseInt(promptMatch[1], 10), v.value)
      }
    }

    // 配对
    for (const [index, modelsStr] of sarModels) {
      const prompt = sarPrompts.get(index)
      if (prompt) {
        pairs.push({
          index,
          models: modelsStr.split(',').map((m) => m.trim().toLowerCase()),
          prompt
        })
      }
    }

    return pairs.sort((a, b) => a.index - b.index)
  }
}

/**
 * 创建 EnvConfigLoader 实例
 */
export function createEnvConfigLoader(): EnvConfigLoader {
  return new EnvConfigLoader()
}

export default EnvConfigLoader
